module.exports = {
  // 'MODELS_DIR': ROOT_DIR + '/models',
  // 'LIBS_DIR': ROOT_DIR + '/libs',
  // 'API_DIR': ROOT_DIR + '/api',
  // 'CONFIG_DIR': ROOT_DIR + '/config',
  // 'CONSTANT_DIR': __dirname,
  'VIDEO_TYPE': 'video',
  'IMAGE_TYPE': 'image',
  'CATEGORY_TYPE': 'category',
  'GALLERY_TYPE': 'gallery',
  'LIVECHANNEL_TYPE': 'liveChannel',
  'POST_TYPE': 'article',
  'PUNDIT_TYPE': 'pundit',
  'FILE_TYPE': 'file',
  'LONGFORM_TYPE': 'longform',
  'NORMAL_TYPE': 'normal',
  'MEDIA_TYPE': 'media',
  'TOURNAMENT_TYPE': 'tournament',
  'SPORT_TYPE': 'sport',
  'TEAM_TYPE': 'team',
  'POST_TYPE_RESPONSE': 'post',
  'VIDEO_TYPE_RESPONSE': 'video',
  'SCHEDULE_TYPE': 'schedule',
  'EVENT_TYPE': 'event',
  'EVENT_TYPE_RESPONSE': 'event'
}
